#!/usr/bin/env python3
"""Regenerate or verify generic engine copies in explicitly supplied caller checkouts."""
import argparse
import hashlib
import json
from pathlib import Path

SOURCE=Path(__file__).resolve().parent
FILES=('workflow_contract.py','workflow_operation.py','pins_compat.mjs')
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('roots',nargs='+',type=Path)
parser.add_argument('--check',action='store_true')
args=parser.parse_args()
for root in args.roots:
    manifest=root/'.github/workflow-contract.json'
    policy=json.loads(manifest.read_text())
    hashes={name:hashlib.sha256((SOURCE/name).read_bytes()).hexdigest() for name in FILES}
    if args.check:
        if policy['engine_sha256']!=hashes: raise SystemExit(f'{root}: engine hashes differ')
        for name in FILES:
            if (root/'.github'/name).is_symlink() or (root/'.github'/name).read_bytes()!=(SOURCE/name).read_bytes():
                raise SystemExit(f'{root}: generated bytes differ: {name}')
    else:
        for name in FILES:
            target=root/'.github'/name
            if target.is_symlink():raise SystemExit(f'{target}: refusing symlink')
            target.write_bytes((SOURCE/name).read_bytes())
        policy['engine_sha256']=hashes
        manifest.write_text(json.dumps(policy,indent=2)+'\n')
    print(f'{root}: generic engine {"verified" if args.check else "regenerated"}')
